name: Clean Sandbox for Production

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  clean-sandbox:
    if: github.head_ref == 'sandbox'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Clean sandbox code
      run: node .github/scripts/clean-sandbox.js

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit changes
      run: |
        git add -A
        git commit -m "Remove sandbox functionality for production" || echo "No changes to commit"

    - name: Push changes to temporary branch
      run: |
        git checkout -b temp-clean-sandbox
        git push origin temp-clean-sandbox --force

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Remove sandbox functionality for production
        title: 'Production: Remove sandbox functionality'
        body: |
          This PR removes sandbox functionality from the code for production deployment.
          Please review the changes and merge if everything looks correct.
        branch: temp-clean-sandbox
        base: main
        labels: production, automated-pr

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
