name: Prepare Pre-Deployment Branch

on:
  push:
    branches:
      - Development

jobs:
  prepare-pre-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Clean sandbox code
      run: node .github/scripts/clean-sandbox.js

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit changes
      run: |
        git add -A
        git commit -m "Prepare pre-deployment code" || echo "No changes to commit"

    - name: Push changes to Pre-Dep branch
      run: |
        git checkout -B Pre-Dep
        git push origin Pre-Dep --force

    - name: Create Pull Request to Pre-Dep
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update Pre-Deployment code
        title: 'Update Pre-Deployment code'
        body: |
          This PR updates the Pre-Deployment branch with the latest cleaned code from Development.
          Please review the changes and merge if everything looks correct.
        branch: Pre-Dep
        base: Pre-Dep
        labels: pre-deployment, automated-pr

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
